### ISSUE TITLE
does not run on arduino nano

### ISSUE THREAD

**Issue by nudlikutya** [Smartheads/AlticraftFlightDataRecorder#1]
stated debug mode, unicode character errors.

-

**Comment by Smartheads** [comment]
Dear nudlikutya!

Thanks for your patience, I've just got the chance to check out your ticket.

I am pleased to announce that I've tweeked the code a little, fixed a few bugs, so that your issue should now be resolved.

If you continue to experience the same issue, please make sure that:
* you are running the latest version of Arduino and FDR,
* you are using an authentic Arduino microcontroller. (Unfortunately I'm only able to help with such devices)

If you continue to experience problems with the program, please reopen this thread.

Sincerely,

Robert
